version: '3.7'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_demo
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

  twitter:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=flaskr
      - FLASK_ENV=development
      - APP_SETTINGS=flaskr.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@twitter-db:5432/twitter_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@twitter-db:5432/twitter_test
    depends_on:
      - twitter-db

  twitter-db:
    build:
      context: ./database
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - twitter-db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin