name: Python Flask Application

on: [push]

jobs:
  verify:
    name: Linting & Testing
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        working-directory: ./rest-backend-python
        run: docker build . --file Dockerfile

      - name: Run flake8 linter
        working-directory: ./rest-backend-python
        run: |
            docker build . --file Dockerfile --target linter -t app-linter
            docker container run --name linter app-linter
            
      - name: Run tests
        working-directory: ./rest-backend-python
        run: |
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
