name: .NET Web App

on:
  push:
    branches: [ main ]
    paths:
    - AzureWebApp

  workflow_dispatch:

env:
  AZURE_WEB_APP_NAME: PDAZE1APIMAS01
  AZURE_WEB_APP_PACKAGE_PATH: './AzureWebApp'
  DOTNET_VERSION: '6.x'

jobs:
  build-and-test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '${{ env.DOTNET_VERSION }}'

    - name: Restore dependencies
      working-directory: "./${{ env.AZURE_WEB_APP_PACKAGE_PATH }}"
      run: dotnet restore

    - name: Build
      working-directory: "./${{ env.AZURE_WEB_APP_PACKAGE_PATH }}"
      run: dotnet build --no-restore

    - name: Test
      working-directory: "./${{ env.AZURE_WEB_APP_PACKAGE_PATH }}"
      run: dotnet test --no-build --verbosity normal


  build-and-deploy:
    runs-on: windows-latest
    environment: dev
    steps:

    # checkout the repo
    - uses: actions/checkout@master

    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: ${{ env.NUGET_VERSION}}
    - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
      run: nuget restore

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Run MSBuild
      run: msbuild .\SampleWebApplication.sln

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/SampleWebApplication/'

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
