name: .NET Web App

on:
  push:
    branches: [ main ]
    paths:
    - AzureWebApp

  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: VSSAZE1PDAS01
  AZURE_WEBAPP_PACKAGE_PATH: './AzureWebApp'
  DOTNET_VERSION: '6.x'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '${{ env.DOTNET_VERSION }}'

    - name: Restore dependencies
      working-directory: "./${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
      run: dotnet restore

    - name: Build
      working-directory: "./${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
      run: dotnet build --no-restore

    - name: Test
      working-directory: "./${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
      run: dotnet test --no-build --verbosity normal


  build-and-deploy:
    needs: 'build-and-test'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        working-directory: "./${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
        run: dotnet restore

      # Run dotnet build and publish
      - name: Build
        working-directory: "./${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
        run: dotnet build --configuration Release

      - name: Publish
        working-directory: "./${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
        run: dotnet publish -c Release -o 'myapp'

      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
